### PR TITLE
fix #91: fix error type

### LINKED ISSUE #91: Clarify better what supported means with regard to the ComputePressureSource enum
Now that we use ComputePressureSource as type instead of DomString, we need to adapt the error return to TypeError.

### PR DESCRIPTION
**Pull request by arskama**
***
<a href="https://pr-preview.s3.amazonaws.com/arskama/compute-pressure/pull/92.html" title="Last updated on Mar 18, 2022, 8:07 AM UTC (b8765d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compute-pressure/92/20f6de4...arskama:b8765d3.html" title="Last updated on Mar 18, 2022, 8:07 AM UTC (b8765d3)">Diff</a>

### CODE REVIEW

**Review by kenchris — COMMENTED** [review]
I think we can just remove the lines as it should be handled by webidl

**Comment by rakuco** [comment]
Hmm, doesn't `NotSupportedError` make more sense here? Web IDL is responsible for checking the values passed to observe() and unobserve() are part of the ComputePressureSource enum, but implementations can then support a subset of the values in the enum, and when script asks for an unsupported source type the implementation can throw a `NotSupportedError`.

**Comment by kenchris** [comment]
WebIDL will ensure that wrong values throw TypeError, so if the enum on one implementation doesn't support, say "ipu", then that platform will throw TypeError.

If a platform supports a version of the spec with "gpu" and "cpu" but the implementation doesn't support "cpu" then we could throw notSupportedError in that case

**Comment by kenchris** [comment]
So yeah, I don't think this PR makes sense. We should probably define what supported means though

**Pull request closed without merging**
